import sys
from PyQt5 import QtWidgets,QtCore,QtGui
def utama():
    def sebelum():
        def ret1():
            wid1.close()
        def lanjut1():
            def ret2():
                wid1a.close()
            def lanjut2():
                def ret3():
                    wid1b.close()
                def lanjut3():
                    def ret4():
                        wid1c.close()
                    def hash():
                        try:
                            satu = int(lenei[0].text())
                            dua = int(lenei[1].text())
                            tiga = int(lenei[2].text())
                            if satu < 0 or dua < 0 or 3 <= 0:
                                raise AssertionError
                        except ValueError:
                            silha.setText("Masukkan Harus Berisikan Angka!!")
                            pulsi.setText("Silahkan Coba Lagi!")
                        except AssertionError:
                            silha.setText("Masukkan Tidak Boleh Negatif!!")
                            pulsi.setText("Silahkan Coba Lagi!")
                        else:
                            resu = dua*satu*tiga
                            lmao = ""
                            if dua > satu:
                                lmao = "Mendapatkan Laba"
                            elif dua < satu:
                                lmao = "Mengalami Kerugian"
                            else:
                                lmao = "Tidak Mendapatkan Apa-Apa"
                            silha.setText(f"Hasil Bersih Sebesar Rp.{resu},00 dalam {tiga} hari")
                            pulsi.setText(f"Maka Anda {lmao}")
                    wid1b.close()
                    wid1c = QtWidgets.QWidget()
                    viba = QtWidgets.QVBoxLayout()
                    heba = QtWidgets.QHBoxLayout()
                    firm = QtWidgets.QFormLayout()
                    # firm.setContentsMargins(0,0,0,30)
                    lab1c = QtWidgets.QLabel("Perencanaan Usaha Untuk Masa Depan!")
                    # lab1c.setContentsMargins(0,30,0,0)
                    lab1c.setAlignment(QtCore.Qt.AlignCenter)
                    lenei = []
                    for i in range(3):
                        i = QtWidgets.QLineEdit()
                        lenei.append(i)
                    lenei[0].setClearButtonEnabled(True)
                    lenei[1].setClearButtonEnabled(True)
                    lenei[2].setClearButtonEnabled(True)
                    lenei[2].returnPressed.connect(hash)
                    pusha = QtWidgets.QPushButton("Hitung")
                    pusha.clicked.connect(hash)
                    pusho = QtWidgets.QPushButton("Kembali")
                    pusho.clicked.connect(ret4)
                    pic = QtGui.QPixmap("ashiap.png")
                    pic = pic.scaledToWidth(250)
                    pix = QtWidgets.QLabel()
                    pix.setPixmap(pic)
                    silha = QtWidgets.QLabel("")
                    silha.setContentsMargins(0,30,0,0)
                    pulsi = QtWidgets.QLabel("")
                    pulsi.setContentsMargins(0,0,0,30)
                    firm.addRow(QtWidgets.QLabel("Harga Per Unit (Rp.)"), lenei[0])
                    firm.addRow(QtWidgets.QLabel("Jumlah Unit (Buah)"), lenei[1])
                    firm.addRow(QtWidgets.QLabel("Lama Waktu Usaha (Hari)"), lenei[2])
                    firm.addRow(pusho,pusha)
                    firm.addRow(silha)
                    firm.addRow(pulsi)
                    viba.addWidget(lab1c)
                    viba.addLayout(firm)
                    heba.addWidget(pix)
                    heba.addLayout(viba)
                    wid1c.setLayout(heba)
                    mawin.setCentralWidget(wid1c)
                    wid1c.show()
                wid1a.close()
                wid1b = QtWidgets.QWidget()
                gredb = QtWidgets.QGridLayout()
                gredb.setContentsMargins(0, 0, 0, 50)
                vibeb = QtWidgets.QVBoxLayout()
                lab1b = QtWidgets.QLabel("Pilih Lokasi Usaha")
                lab1b.setAlignment(QtCore.Qt.AlignCenter)
                rad0b = QtWidgets.QRadioButton("Perumahan")
                rad1b = QtWidgets.QRadioButton("Tempat Umum")
                rad2b = QtWidgets.QRadioButton("Perkotaan")
                rad3b = QtWidgets.QRadioButton("Online")
                rad0b.setChecked(True)
                pusib = QtWidgets.QPushButton("Lanjut")
                puseb = QtWidgets.QPushButton("Kembali")
                pusib.clicked.connect(lanjut3)
                puseb.clicked.connect(ret3)
                pic = QtGui.QPixmap("ashiap.png")
                pic = pic.scaledToWidth(250)
                pix = QtWidgets.QLabel()
                pix.setPixmap(pic)
                gredb.addWidget(rad0b, 1, 0, 1, 0)
                gredb.addWidget(rad1b, 2, 0, 1, 0)
                gredb.addWidget(rad2b, 3, 0, 1, 0)
                gredb.addWidget(rad3b, 4, 0, 1, 0)
                gredb.addWidget(pusib, 5, 0)
                gredb.addWidget(puseb, 5, 1)
                vibeb.addWidget(lab1b)
                vibeb.addLayout(gredb)
                hbob = QtWidgets.QHBoxLayout()
                hbob.addWidget(pix)
                hbob.addLayout(vibeb)
                wid1b.setLayout(hbob)
                mawin.setCentralWidget(wid1b)
                wid1b.show()
            wid1.close()
            wid1a = QtWidgets.QWidget()
            greda = QtWidgets.QGridLayout()
            greda.setContentsMargins(0, 0, 0, 50)
            vibea = QtWidgets.QVBoxLayout()
            lab1a = QtWidgets.QLabel("Pilih Jenis Target Konsumen")
            lab1a.setAlignment(QtCore.Qt.AlignCenter)
            rad0a = QtWidgets.QRadioButton("Balita")
            rad1a = QtWidgets.QRadioButton("Anak-Anak")
            rad2a = QtWidgets.QRadioButton("Remaja")
            rad3a = QtWidgets.QRadioButton("Dewasa")
            rad0a.setChecked(True)
            pusia = QtWidgets.QPushButton("Lanjut")
            pusea = QtWidgets.QPushButton("Kembali")
            pusia.clicked.connect(lanjut2)
            puse.clicked.connect(ret2)
            pic = QtGui.QPixmap("ashiap.png")
            pic = pic.scaledToWidth(250)
            pix = QtWidgets.QLabel()
            pix.setPixmap(pic)
            greda.addWidget(rad0a, 1, 0, 1, 0)
            greda.addWidget(rad1a, 2, 0, 1, 0)
            greda.addWidget(rad2a, 3, 0, 1, 0)
            greda.addWidget(rad3a, 4, 0, 1, 0)
            greda.addWidget(pusia, 5, 0)
            greda.addWidget(pusea, 5, 1)
            vibea.addWidget(lab1a)
            vibea.addLayout(greda)
            hboa = QtWidgets.QHBoxLayout()
            hboa.addWidget(pix)
            hboa.addLayout(vibea)
            wid1a.setLayout(hboa)
            mawin.setCentralWidget(wid1a)
            wid1a.show()
        wid.close()
        wid1 = QtWidgets.QWidget()
        gred = QtWidgets.QGridLayout()
        gred.setContentsMargins(0, 0, 0, 50)
        vibe = QtWidgets.QVBoxLayout()
        lab1 = QtWidgets.QLabel("Pilih Jenis Produk Usaha")
        lab1.setAlignment(QtCore.Qt.AlignCenter)
        rad0 = QtWidgets.QRadioButton("Makanan/Minuman")
        rad1 = QtWidgets.QRadioButton("Perabotan/Peralatan")
        rad2 = QtWidgets.QRadioButton("Pelayanan/Jasa")
        rad3 = QtWidgets.QRadioButton("Game/Virtual")
        rad0.setChecked(True)
        pusi = QtWidgets.QPushButton("Lanjut")
        puse = QtWidgets.QPushButton("Kembali")
        pusi.clicked.connect(lanjut1)
        puse.clicked.connect(ret1)
        pic = QtGui.QPixmap("ashiap.png")
        pic = pic.scaledToWidth(250)
        pix = QtWidgets.QLabel()
        pix.setPixmap(pic)
        gred.addWidget(rad0, 1, 0, 1, 0)
        gred.addWidget(rad1, 2, 0, 1, 0)
        gred.addWidget(rad2, 3, 0, 1, 0)
        gred.addWidget(rad3, 4, 0, 1, 0)
        gred.addWidget(pusi, 5, 0)
        gred.addWidget(puse, 5, 1)
        vibe.addWidget(lab1)
        vibe.addLayout(gred)
        hbo = QtWidgets.QHBoxLayout()
        hbo.addWidget(pix)
        hbo.addLayout(vibe)
        wid1.setLayout(hbo)
        mawin.setCentralWidget(wid1)
        wid1.show()
    def sesudah():
        def bek():
            wid2.close()
        def hitung():
            try:
                satu = int(ledit[0].text())
                dua = int(ledit[1].text())
                tiga = int(ledit[2].text())
                if satu<0 or dua<0 or 3<=0 :
                    raise AssertionError
            except ValueError:
                hasil.setText("Masukkan Harus Berisikan Angka!!")
                kesi.setText("Silahkan Coba Lagi!")
            except AssertionError:
                hasil.setText("Masukkan Tidak Boleh Negatif!!")
                kesi.setText("Silahkan Coba Lagi!")
            else:
                resu = (dua-satu)*tiga
                lmao = ""
                if dua>satu :
                    lmao = "Mendapatkan Laba"
                elif dua<satu :
                    lmao = "Mengalami Kerugian"
                else:
                    lmao = "Tidak Mendapatkan Apa-Apa"
                hasil.setText(f"Hasil Bersih Sebesar Rp.{resu},00 dalam {tiga} hari")
                kesi.setText(f"Maka Anda {lmao}")
        wid.close()
        wid2 = QtWidgets.QWidget()
        frm = QtWidgets.QFormLayout()
        labi = QtWidgets.QLabel("Perhitungan Setelah Usaha")
        labi.setAlignment(QtCore.Qt.AlignCenter)
        pusi = QtWidgets.QPushButton("Hitung")
        puse = QtWidgets.QPushButton("Kembali")
        pusi.clicked.connect(hitung)
        puse.clicked.connect(bek)
        pic = QtGui.QPixmap("ashiap.png")
        pic = pic.scaledToWidth(250)
        pix = QtWidgets.QLabel()
        pix.setPixmap(pic)
        hasil = QtWidgets.QLabel("")
        hasil.setContentsMargins(0,30,0,0)
        kesi = QtWidgets.QLabel("")
        kesi.setContentsMargins(0,0,0,30)
        ledit = []
        for i in range(3):
            i = QtWidgets.QLineEdit()
            ledit.append(i)
        ledit[0].setClearButtonEnabled(True)
        ledit[1].setClearButtonEnabled(True)
        ledit[2].setClearButtonEnabled(True)
        ledit[2].returnPressed.connect(hitung)
        hbo = QtWidgets.QHBoxLayout()
        frm.addRow(QtWidgets.QLabel("Total Seluruh Modal (Rp.)"), ledit[0])
        frm.addRow(QtWidgets.QLabel("Total Seluruh Hasil (Rp.)"), ledit[1])
        frm.addRow(QtWidgets.QLabel("Lama Waktu Usaha (Hari)"), ledit[2])
        frm.addRow(puse,pusi)
        frm.addRow(hasil)
        frm.addRow(kesi)
        vbo = QtWidgets.QVBoxLayout()
        vbo.addWidget(labi)
        vbo.addLayout(frm)
        hbo.addWidget(pix)
        hbo.addLayout(vbo)
        wid2.setLayout(hbo)
        mawin.setCentralWidget(wid2)
        wid2.show()
    app = QtWidgets.QApplication([])
    mawin = QtWidgets.QMainWindow()
    mawin.setWindowTitle("Aplikasi Laba")
    ikon = QtGui.QIcon("ashiap.png")
    grid1 = QtWidgets.QGridLayout()
    herb = QtWidgets.QHBoxLayout()
    herb.setContentsMargins(0,0,0,100)
    labtop = QtWidgets.QLabel("Pilih Perhitungan Sebelum atau Sesudah Berwirausaha!")
    labtop.setContentsMargins(0,30,0,0)
    push1 = QtWidgets.QPushButton("Sebelum")
    push2 = QtWidgets.QPushButton("Sesudah")
    # push2.setContentsMargins(0,0,0,40)
    push1.clicked.connect(sebelum)
    push2.clicked.connect(sesudah)
    pic = QtGui.QPixmap("ashiap.png")
    pic = pic.scaledToWidth(250)
    pix = QtWidgets.QLabel()
    pix.setPixmap(pic)
    herb.addWidget(push1)
    herb.addWidget(push2)
    hebo = QtWidgets.QHBoxLayout()
    grid1.addWidget(labtop,0,0)
    grid1.addLayout(herb,1,0)
    hebo.addWidget(pix)
    hebo.addLayout(grid1)
    wid = QtWidgets.QWidget()
    wid.setLayout(hebo)
    mawin.setWindowIcon(ikon)
    mawin.setCentralWidget(wid)
    mawin.show()
    sys.exit(app.exec_())
if __name__ == '__main__':
    utama()